# Uncomment this line to define a global platform for your project
 platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TMDB' do
pod 'AFNetworking', '~> 3.0'
pod ‘Mantle’
pod 'SDWebImage', '~>3.8'
end

target ‘TMDBTests’ do
pod 'AFNetworking', '~> 3.0'
pod ‘Mantle’
pod 'SDWebImage', '~>3.8'
end 

